<?php
namespace Hypertable_ThriftGen;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Specifies a range of cells
 * 
 * <dl>
 *   <dt>start_row</dt>
 *   <dd>The row to start scan with. Must not contain nulls (0x00)</dd>
 * 
 *   <dt>start_column</dt>
 *   <dd>The column (prefix of column_family:column_qualifier) of the
 *   start row for the scan</dd>
 * 
 *   <dt>start_inclusive</dt>
 *   <dd>Whether the start row is included in the result (default: true)</dd>
 * 
 *   <dt>end_row</dt>
 *   <dd>The row to end scan with. Must not contain nulls</dd>
 * 
 *   <dt>end_column</dt>
 *   <dd>The column (prefix of column_family:column_qualifier) of the
 *   end row for the scan</dd>
 * 
 *   <dt>end_inclusive</dt>
 *   <dd>Whether the end row is included in the result (default: true)</dd>
 * </dl>
 */
class CellInterval
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'start_row',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'start_column',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'start_inclusive',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        4 => array(
            'var' => 'end_row',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        5 => array(
            'var' => 'end_column',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        6 => array(
            'var' => 'end_inclusive',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
    );

    /**
     * @var string
     */
    public $start_row = null;
    /**
     * @var string
     */
    public $start_column = null;
    /**
     * @var bool
     */
    public $start_inclusive = true;
    /**
     * @var string
     */
    public $end_row = null;
    /**
     * @var string
     */
    public $end_column = null;
    /**
     * @var bool
     */
    public $end_inclusive = true;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['start_row'])) {
                $this->start_row = $vals['start_row'];
            }
            if (isset($vals['start_column'])) {
                $this->start_column = $vals['start_column'];
            }
            if (isset($vals['start_inclusive'])) {
                $this->start_inclusive = $vals['start_inclusive'];
            }
            if (isset($vals['end_row'])) {
                $this->end_row = $vals['end_row'];
            }
            if (isset($vals['end_column'])) {
                $this->end_column = $vals['end_column'];
            }
            if (isset($vals['end_inclusive'])) {
                $this->end_inclusive = $vals['end_inclusive'];
            }
        }
    }

    public function getName()
    {
        return 'CellInterval';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->start_row);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->start_column);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->start_inclusive);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->end_row);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->end_column);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->end_inclusive);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('CellInterval');
        if ($this->start_row !== null) {
            $xfer += $output->writeFieldBegin('start_row', TType::STRING, 1);
            $xfer += $output->writeString($this->start_row);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->start_column !== null) {
            $xfer += $output->writeFieldBegin('start_column', TType::STRING, 2);
            $xfer += $output->writeString($this->start_column);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->start_inclusive !== null) {
            $xfer += $output->writeFieldBegin('start_inclusive', TType::BOOL, 3);
            $xfer += $output->writeBool($this->start_inclusive);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->end_row !== null) {
            $xfer += $output->writeFieldBegin('end_row', TType::STRING, 4);
            $xfer += $output->writeString($this->end_row);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->end_column !== null) {
            $xfer += $output->writeFieldBegin('end_column', TType::STRING, 5);
            $xfer += $output->writeString($this->end_column);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->end_inclusive !== null) {
            $xfer += $output->writeFieldBegin('end_inclusive', TType::BOOL, 6);
            $xfer += $output->writeBool($this->end_inclusive);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
