<?php
namespace Hypertable_ThriftGen;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ColumnFamilyOptions
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'max_versions',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'ttl',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'time_order_desc',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        4 => array(
            'var' => 'counter',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
    );

    /**
     * @var int
     */
    public $max_versions = null;
    /**
     * @var int
     */
    public $ttl = null;
    /**
     * @var bool
     */
    public $time_order_desc = null;
    /**
     * @var bool
     */
    public $counter = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['max_versions'])) {
                $this->max_versions = $vals['max_versions'];
            }
            if (isset($vals['ttl'])) {
                $this->ttl = $vals['ttl'];
            }
            if (isset($vals['time_order_desc'])) {
                $this->time_order_desc = $vals['time_order_desc'];
            }
            if (isset($vals['counter'])) {
                $this->counter = $vals['counter'];
            }
        }
    }

    public function getName()
    {
        return 'ColumnFamilyOptions';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->max_versions);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->ttl);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->time_order_desc);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->counter);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ColumnFamilyOptions');
        if ($this->max_versions !== null) {
            $xfer += $output->writeFieldBegin('max_versions', TType::I32, 1);
            $xfer += $output->writeI32($this->max_versions);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ttl !== null) {
            $xfer += $output->writeFieldBegin('ttl', TType::I32, 2);
            $xfer += $output->writeI32($this->ttl);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->time_order_desc !== null) {
            $xfer += $output->writeFieldBegin('time_order_desc', TType::BOOL, 3);
            $xfer += $output->writeBool($this->time_order_desc);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->counter !== null) {
            $xfer += $output->writeFieldBegin('counter', TType::BOOL, 4);
            $xfer += $output->writeBool($this->counter);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
