<?php
namespace Hypertable_ThriftGen;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Defines a table split
 * 
 * <dl>
 *   <dt>start_row</dt>
 *   <dd>Starting row of the split.</dd>
 * 
 *   <dt>end_row</dt>
 *   <dd>Ending row of the split.</dd>
 * 
 *   <dt>location</dt>
 *   <dd>Location (proxy name) of the split.</dd>
 * 
 *   <dt>ip_address</dt>
 *   <dd>The IP address of the split.</dd>
 * 
 *   <dt>hostname</dt>
 *   <dd>The hostname of the split.</dd>
 * </dl>
 */
class TableSplit
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'start_row',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'end_row',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'location',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'ip_address',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        5 => array(
            'var' => 'hostname',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $start_row = null;
    /**
     * @var string
     */
    public $end_row = null;
    /**
     * @var string
     */
    public $location = null;
    /**
     * @var string
     */
    public $ip_address = null;
    /**
     * @var string
     */
    public $hostname = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['start_row'])) {
                $this->start_row = $vals['start_row'];
            }
            if (isset($vals['end_row'])) {
                $this->end_row = $vals['end_row'];
            }
            if (isset($vals['location'])) {
                $this->location = $vals['location'];
            }
            if (isset($vals['ip_address'])) {
                $this->ip_address = $vals['ip_address'];
            }
            if (isset($vals['hostname'])) {
                $this->hostname = $vals['hostname'];
            }
        }
    }

    public function getName()
    {
        return 'TableSplit';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->start_row);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->end_row);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->location);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->ip_address);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->hostname);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('TableSplit');
        if ($this->start_row !== null) {
            $xfer += $output->writeFieldBegin('start_row', TType::STRING, 1);
            $xfer += $output->writeString($this->start_row);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->end_row !== null) {
            $xfer += $output->writeFieldBegin('end_row', TType::STRING, 2);
            $xfer += $output->writeString($this->end_row);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->location !== null) {
            $xfer += $output->writeFieldBegin('location', TType::STRING, 3);
            $xfer += $output->writeString($this->location);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ip_address !== null) {
            $xfer += $output->writeFieldBegin('ip_address', TType::STRING, 4);
            $xfer += $output->writeString($this->ip_address);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->hostname !== null) {
            $xfer += $output->writeFieldBegin('hostname', TType::STRING, 5);
            $xfer += $output->writeString($this->hostname);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
