<?php
namespace Hypertable_ThriftGen2;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Same as HqlResult except with cell as array
 */
class HqlResultAsArrays
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'results',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
        2 => array(
            'var' => 'cells',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::LST,
            'elem' => array(
                'type' => TType::LST,
                'etype' => TType::STRING,
                'elem' => array(
                    'type' => TType::STRING,
                    ),
                ),
        ),
        3 => array(
            'var' => 'scanner',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        4 => array(
            'var' => 'mutator',
            'isRequired' => false,
            'type' => TType::I64,
        ),
    );

    /**
     * @var string[]
     */
    public $results = null;
    /**
     * @var string[][]
     */
    public $cells = null;
    /**
     * @var int
     */
    public $scanner = null;
    /**
     * @var int
     */
    public $mutator = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['results'])) {
                $this->results = $vals['results'];
            }
            if (isset($vals['cells'])) {
                $this->cells = $vals['cells'];
            }
            if (isset($vals['scanner'])) {
                $this->scanner = $vals['scanner'];
            }
            if (isset($vals['mutator'])) {
                $this->mutator = $vals['mutator'];
            }
        }
    }

    public function getName()
    {
        return 'HqlResultAsArrays';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::LST) {
                        $this->results = array();
                        $_size35 = 0;
                        $_etype38 = 0;
                        $xfer += $input->readListBegin($_etype38, $_size35);
                        for ($_i39 = 0; $_i39 < $_size35; ++$_i39) {
                            $elem40 = null;
                            $xfer += $input->readString($elem40);
                            $this->results []= $elem40;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::LST) {
                        $this->cells = array();
                        $_size41 = 0;
                        $_etype44 = 0;
                        $xfer += $input->readListBegin($_etype44, $_size41);
                        for ($_i45 = 0; $_i45 < $_size41; ++$_i45) {
                            $elem46 = null;
                            $elem46 = array();
                            $_size47 = 0;
                            $_etype50 = 0;
                            $xfer += $input->readListBegin($_etype50, $_size47);
                            for ($_i51 = 0; $_i51 < $_size47; ++$_i51) {
                                $elem52 = null;
                                $xfer += $input->readString($elem52);
                                $elem46 []= $elem52;
                            }
                            $xfer += $input->readListEnd();
                            $this->cells []= $elem46;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->scanner);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->mutator);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('HqlResultAsArrays');
        if ($this->results !== null) {
            if (!is_array($this->results)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('results', TType::LST, 1);
            $output->writeListBegin(TType::STRING, count($this->results));
            foreach ($this->results as $iter53) {
                $xfer += $output->writeString($iter53);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->cells !== null) {
            if (!is_array($this->cells)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('cells', TType::LST, 2);
            $output->writeListBegin(TType::LST, count($this->cells));
            foreach ($this->cells as $iter54) {
                $output->writeListBegin(TType::STRING, count($iter54));
                foreach ($iter54 as $iter55) {
                    $xfer += $output->writeString($iter55);
                }
                $output->writeListEnd();
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->scanner !== null) {
            $xfer += $output->writeFieldBegin('scanner', TType::I64, 3);
            $xfer += $output->writeI64($this->scanner);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->mutator !== null) {
            $xfer += $output->writeFieldBegin('mutator', TType::I64, 4);
            $xfer += $output->writeI64($this->mutator);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
